xxd -i -n png_font font.png > png_font.h
xxd -i -n png_tile tile.png > png_tile.h
xxd -i -n png_logo_sms logo_sms.png > png_logo_sms.h
xxd -i -n png_logo_coleco logo_coleco.png > png_logo_coleco.h
xxd -i -n png_logo_gg logo_gg.png > png_logo_gg.h
xxd -i -n png_gamepad_sms gamepad_sms.png > png_gamepad_sms.h
xxd -i -n png_gamepad_gg gamepad_gg.png > png_gamepad_gg.h
xxd -i -n png_gamepad_coleco gamepad_coleco.png > png_gamepad_coleco.h
xxd -i -n png_backdrop backdrop.png > png_backdrop.h